# Setup
title:        Max Fefer, EIT
tagline:      Aspiring water engineer

# About/contact
author:
  name:       Max Fefer
  url:        mfefer.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

#Others
markdown: kramdown